create table records
(
    id bigint generated by default as identity,
    Bookinfo_bookname varchar(50),
    date date,
    inspirations varchar(300),
    pages int,
    primary key (id),
    foreign key (Bookinfo_bookname) references Bookinfo(bookname)
);