create table records
(
    id bigint generated by default as identity,
    Bookinfo_id bigint,
    date date,
    inspirations varchar(300),
    pages int,
    primary key (id),
    foreign key (Bookinfo_id) references Bookinfo(id)
);